[package]
name = "rust_line_bot"
version = "0.1.0"
authors = ["Yamato Ashikaga <a.yamato.so.ri.00@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
